spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: review-service-router
              uri: lb://review-service  #http://localhost:8080
              predicates:
                - Path=/api/v1/reviews/**,/api/v2/reviews/**

            - id: order-service-router
              uri: lb://order-service
              predicates:
                - Path=/api/v1/orders/**
            - id: product-service-router
              uri: lb://product-service
              predicates:
                - Path=/api/v1/products/**
server:
  port: 8888

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

