spring:
  application:
    name: gateway-server
  profiles:
    active: dev
  config:
    import: "configserver:${CONFIG_URI:http://localhost:8787}"


# profiles.active =>
# CONFIG_URI => https://config-server.turkcell.com.tr