version: '3.8'

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-3
    ports:
      - "8079:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-host-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: host.docker.internal:29023
    restart: unless-stopped