openapi: 3.0.3
info:
  title: Review Service API
  description: API mor managing product reviews.
  version: 1.0.0

servers:
  - url: http://localhost:8085
    description: Local development server

paths:
  /api/v1/reviews:
    post:
      tags: [ Reviews ]
      summary: Create a review
      description: >
        "This endpoint creates a new review for the specified product."
      operationId: createReview
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateReviewRequest' }
      responses:
        '201':
          description: CREATED
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: { type: string, format: uuid }
                  productId: { type: string, format: uuid }
                  rate: { type: number, minimum: 1, maximum: 5 }
                  description: { type: string, maxLength: 255 }
components:
  schemas:
    CreateReviewRequest:
      type: object
      required: [productId, rate, description]
      properties:
        productId: { type: string, format: uuid }
        rate: { type: number, minimum: 1, maximum: 5 }
        description: { type: string, maxLength: 255 }
