spring:
  application:
    name: product-service
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:C:/Users/PC1/product-db;
    username: sa
    password:
  kafka:
    bootstrap-servers: localhost:9094
  cloud:
    function:
      definition: processOrder
    stream:
      bindings:
        processOrder-in-0:
          destination: orders
          content-type: application/json
          group: product-service
          consumer:
            max-attempts: 5
            back-off-initial-interval: 1000
            back-off-multiplier: 2.0
            back-off-max-interval: 30000
      kafka:
        bindings:
          processOrder-in-0:
            consumer:
              enable-dlq: true
              # error.<destination>.<group>
              #dlq-name: orders.notification.dlq
server:
  port: 8082

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/